taxi.settings:
  type: config_object
  label: 'Taxi timer settings'
  mapping:
    timer:
      type: mapping
      label: 'Timer'
      mapping:
        enable:
          type: boolean
          label: 'Show after submit form or no'
        mes_head:
          type: label
          label: 'Title message'
        mes_text:
          type: text
          label: 'Basic text message'
        position:
          type: label
          label: 'Where must show notify block'
